const fs = require('fs');

const questionsFile = './src/data/questions.json';
const data = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));

const newQuestions = [
  { "id": 206, "chapter": 6, "topic": "Integración de Herramientas", "difficulty": "hard", "question": "¿Qué es la 'Intrusión' (Probe Effect) de una herramienta de prueba?", "options": [ "A) Cuando la herramienta hackea la base de datos.", "B) El efecto involuntario donde la herramienta cambia el comportamiento del software que está probando, ocultando un defecto o introduciendo uno falso.", "C) Cuando la herramienta es muy cara.", "D) El análisis del código fuente." ], "correctAnswer": 1, "explanation": "La intrusión ocurre, por ejemplo, cuando una herramienta de cobertura ralentiza tanto el sistema que hace que fallen las pruebas de tiempo límite (Timeouts) que en producción real no fallarían." },
  { "id": 207, "chapter": 1, "topic": "Proceso", "difficulty": "easy", "question": "En el proceso de pruebas, la creación de 'Datos de Prueba' (Test Data) se realiza típicamente durante:", "options": [ "A) La Planificación.", "B) El Análisis.", "C) La Implementación de Pruebas (Test Implementation).", "D) El Cierre." ], "correctAnswer": 2, "explanation": "Durante la implementación, se ensamblan los casos de prueba en procedimientos (scripts) y se preparan todos los datos reales (BBDD, archivos XML) necesarios para ejecutarlos." },
  { "id": 208, "chapter": 2, "topic": "Modelos Secuenciales", "difficulty": "medium", "question": "¿Cuál de las siguientes afirmaciones describe mejor al Modelo en V?", "options": [ "A) Es una metodología puramente ágil.", "B) Es un modelo iterativo que no requiere documentación.", "C) Es un modelo secuencial donde cada fase de desarrollo tiene un nivel de prueba asociado y las pruebas tempranas (estáticas) son enfatizadas.", "D) Es un modelo caótico." ], "correctAnswer": 2, "explanation": "El Modelo en V ilustra cómo las pruebas deben integrarse desde el principio, vinculando requisitos con UAT, diseño de arquitectura con Integración, etc." },
  { "id": 209, "chapter": 3, "topic": "Revisiones Estáticas", "difficulty": "medium", "question": "¿Qué factor psicológico es el mayor riesgo para el éxito de una revisión formal de código?", "options": [ "A) Falta de café.", "B) Que el autor tome las críticas al documento como un ataque personal a sus habilidades.", "C) Que el código esté en Python.", "D) El tamaño del proyector." ], "correctAnswer": 1, "explanation": "Si el ambiente de revisión no es constructivo y diplomático, los desarrolladores se pondrán a la defensiva y la revisión se convertirá en una discusión tóxica." },
  { "id": 210, "chapter": 4, "topic": "Cobertura de Condiciones", "difficulty": "hard", "question": "¿La cobertura de condiciones múltiples garantiza siempre la cobertura de sentencias?", "options": [ "A) Sí.", "B) No, no tienen relación.", "C) Solo en pruebas estáticas.", "D) Depende del lenguaje de programación." ], "correctAnswer": 0, "explanation": "La cobertura de condiciones múltiples (evaluar todas las combinaciones lógicas Verdadero/Falso) es la más exhaustiva de las pruebas estructurales, subsumiendo a la de decisiones y sentencias." },
  { "id": 211, "chapter": 5, "topic": "Estimación de Pruebas", "difficulty": "medium", "question": "¿Qué riesgo puede afectar negativamente a tus estimaciones de esfuerzo de prueba?", "options": [ "A) Entornos de prueba inestables o que fallan constantemente.", "B) Testers con demasiada experiencia.", "C) Especificaciones excesivamente claras y concisas.", "D) Usar herramientas de automatización de alta calidad." ], "correctAnswer": 0, "explanation": "Si el entorno se cae, los testers no pueden ejecutar pruebas. Esto consume tiempo del presupuesto y retrasa todo el plan original." },
  { "id": 212, "chapter": 6, "topic": "Métricas de Herramientas", "difficulty": "easy", "question": "¿Las herramientas de análisis estático pueden reportar la 'Complejidad Ciclomática'?", "options": [ "A) Sí, es una de sus funciones principales al analizar la estructura del código.", "B) No, solo cuentan las líneas de código.", "C) Sí, pero debes ejecutar la aplicación primero.", "D) No, esto lo hacen las herramientas de rendimiento." ], "correctAnswer": 0, "explanation": "Los analizadores estáticos pueden calcular ecuaciones matemáticas (como la métrica de McCabe) escaneando las estructuras lógicas (ifs, fors) directamente en el texto del código." },
  { "id": 213, "chapter": 1, "topic": "Calidad", "difficulty": "medium", "question": "¿Por qué el QA (Aseguramiento de la Calidad) debe ser independiente del QC (Control de Calidad)?", "options": [ "A) Porque QC no sirve para nada.", "B) Porque QA define las normas y audita que se sigan; si también probaran (QC), se auditarían a sí mismos (conflicto de intereses).", "C) QA solo hace marketing.", "D) Son exactamente la misma persona siempre." ], "correctAnswer": 1, "explanation": "QA establece los estándares de calidad del proyecto. Si un equipo establece sus propios estándares y es el único que verifica su cumplimiento, se pierde la objetividad." },
  { "id": 214, "chapter": 2, "topic": "Niveles de Prueba", "difficulty": "medium", "question": "¿Qué pruebas verifican las interfaces entre el software de la empresa y componentes de hardware o sistemas operativos externos?", "options": [ "A) Pruebas de Sistema.", "B) Pruebas de Aceptación (UAT).", "C) Pruebas de Integración de Sistemas.", "D) Pruebas Alfa." ], "correctAnswer": 2, "explanation": "La integración de sistemas abarca no solo software de terceros (APIs), sino también bases de datos externas, hardware (lectores de tarjetas) y SSO." },
  { "id": 215, "chapter": 3, "topic": "Análisis Estático", "difficulty": "easy", "question": "¿Cuál es un defecto típico que el Análisis Estático detectará de forma casi inmediata pero las pruebas dinámicas podrían tardar semanas en revelar?", "options": [ "A) El logotipo tiene un color rojo equivocado.", "B) Vulnerabilidades de seguridad por buffer overflow o variables no declaradas (Security Flaws).", "C) El usuario no sabe usar la interfaz.", "D) La pasarela de pagos rechaza tarjetas de Francia." ], "correctAnswer": 1, "explanation": "El análisis estático escanea la arquitectura buscando patrones de inyección SQL, desbordamientos de buffer o fugas de memoria, cosas invisibles a simple vista." },
  { "id": 216, "chapter": 4, "topic": "Particiones", "difficulty": "hard", "question": "Un programa clasifica estudiantes en Infantil (3-5 años), Primaria (6-11), Secundaria (12-16). Edades menores a 3 o mayores a 16 muestran error. Si se diseñan pruebas con un representante de cada clase válida e inválida, ¿cuántos casos de prueba se necesitan?", "options": [ "A) 3", "B) 4", "C) 5", "D) 6" ], "correctAnswer": 2, "explanation": "Las clases son: [Menor 3], [3 a 5], [6 a 11], [12 a 16], [Mayor 16]. Esto son 2 inválidas y 3 válidas, total = 5." },
  { "id": 217, "chapter": 5, "topic": "Métricas", "difficulty": "medium", "question": "¿Qué indica un aumento repentino en la 'Densidad de Defectos' en un módulo del código antes del lanzamiento?", "options": [ "A) Que el módulo está listo.", "B) Que es un área de alto riesgo técnico y probablemente el diseño inicial fue deficiente o demasiado complejo.", "C) Que las pruebas deben detenerse.", "D) Que el código es perfecto." ], "correctAnswer": 1, "explanation": "Muchos bugs en una misma pieza pequeña de código indican mala arquitectura, deuda técnica y el cumplimiento de la ley 'Agrupación de defectos'." },
  { "id": 218, "chapter": 6, "topic": "ROI", "difficulty": "medium", "question": "Si una empresa cambia su interfaz gráfica cada 2 semanas (colores, botones, estructura de menús), automatizar la interfaz gráfica usando grabadoras de macros (Capture-Playback) es:", "options": [ "A) Una excelente inversión.", "B) Una pérdida de tiempo y dinero debido al enorme costo de mantenimiento constante (Fragilidad de pruebas).", "C) La única forma de probar.", "D) Recomendado por ISTQB." ], "correctAnswer": 1, "explanation": "Los scripts de Capture-Playback se rompen fácilmente. Si la UI cambia, tendrás que grabar las pruebas de nuevo, perdiendo todo el ROI de la automatización." },
  { "id": 219, "chapter": 1, "topic": "Objetivos de Pruebas", "difficulty": "easy", "question": "¿Las pruebas buscan probar que el desarrollador hizo un mal trabajo?", "options": [ "A) Sí, ese es su objetivo final.", "B) No, su objetivo es evaluar la calidad y reducir el riesgo para asegurar que el sistema es seguro y usable, con mentalidad de equipo.", "C) Sí, para pedir reembolsos.", "D) Nunca buscan defectos." ], "correctAnswer": 1, "explanation": "El fin último del testing es entregar un producto con la calidad esperada al cliente, trabajando en sintonía con desarrollo." },
  { "id": 220, "chapter": 2, "topic": "Pruebas Estructurales", "difficulty": "hard", "question": "En un enfoque de BDD (Behavior-Driven Development), los niveles de prueba son impulsados por:", "options": [ "A) El código fuente interno.", "B) El comportamiento deseado del sistema descrito en lenguaje natural comprensible por el negocio (ej. Given-When-Then).", "C) Diagramas de base de datos.", "D) Adivinación." ], "correctAnswer": 1, "explanation": "BDD usa especificaciones ejecutables (Cucumber, Gherkin) para que el comportamiento del negocio sea la guía unificada para codificar y probar simultáneamente." },
  { "id": 221, "chapter": 3, "topic": "Revisiones Estáticas", "difficulty": "medium", "question": "¿Qué factor NO influye en el éxito de una revisión técnica?", "options": [ "A) Apoyo de la alta dirección al proceso de revisión.", "B) Usar listas de comprobación.", "C) Elegir a los revisores correctos y capacitados.", "D) Celebrar la reunión sin preparar el documento de antemano para que sea 'espontánea'." ], "correctAnswer": 3, "explanation": "La 'preparación individual' es el paso MÁS crítico en las revisiones formales. Sin haber leído el documento, la reunión es inútil." },
  { "id": 222, "chapter": 4, "topic": "Tabla de Decisión", "difficulty": "medium", "question": "Las tablas de decisión son excepcionalmente útiles para probar:", "options": [ "A) Reglas de negocio complejas y validaciones del sistema con múltiples entradas y salidas dependientes.", "B) Bases de datos masivas.", "C) La velocidad de la CPU.", "D) Pruebas de estrés." ], "correctAnswer": 0, "explanation": "Cuando una regla de negocio dice 'Si el cliente es VIP y su saldo es X y la fecha es Y, entonces el descuento es Z', una tabla de decisión mapea esto sin perder combinaciones lógicas." },
  { "id": 223, "chapter": 5, "topic": "Riesgos de Producto", "difficulty": "easy", "question": "Si en la aplicación médica que estás probando, el cálculo de las dosis de medicina puede fallar. Esto es:", "options": [ "A) Riesgo de Proyecto.", "B) Riesgo de Producto con severidad Crítica/Life-threatening.", "C) Fuga de memoria.", "D) Riesgo Comercial." ], "correctAnswer": 1, "explanation": "Afecta a la seguridad directa del usuario (Safety). El riesgo de producto aquí está en el rango más alto de severidad e impacto legal." },
  { "id": 224, "chapter": 6, "topic": "Uso de Herramientas", "difficulty": "medium", "question": "¿Las herramientas de prueba deberían adoptarse rápidamente (Big Bang) en toda la organización para ver resultados rápidos?", "options": [ "A) Sí, para aprovechar la licencia.", "B) No, deben ser introducidas progresivamente (roll-out), comenzando con un proyecto piloto, adaptando procesos y entrenando al equipo.", "C) Sí, porque las herramientas son plug-and-play.", "D) No, deben ser escondidas a la gerencia." ], "correctAnswer": 1, "explanation": "Una adopción masiva sin adaptación cultural y técnica asegura el fracaso de la herramienta en la empresa (Shelfware)." },
  { "id": 225, "chapter": 1, "topic": "Independencia", "difficulty": "hard", "question": "¿Un alto grado de independencia del equipo de pruebas tiene alguna desventaja?", "options": [ "A) No, es perfecto.", "B) Sí, el equipo independiente puede aislarse, causar cuellos de botella y perder entendimiento del negocio, volviéndose adversarios del desarrollo.", "C) Sí, cuesta menos.", "D) Hace que las herramientas no funcionen." ], "correctAnswer": 1, "explanation": "La independencia total (como los QA externos) puede derivar en una cultura de 'nosotros contra ellos' y aislamiento técnico que retrasa los despliegues (el famoso muro)." },
  { "id": 226, "chapter": 2, "topic": "Pruebas de Componente", "difficulty": "medium", "question": "En las pruebas de componente, se suelen usar 'Mocks' (Objetos simulados) para:", "options": [ "A) Falsificar informes.", "B) Reemplazar componentes dependientes que no están disponibles o son lentos (ej. bases de datos reales o APIs externas).", "C) Simular ataques hackers.", "D) Cifrar el código fuente." ], "correctAnswer": 1, "explanation": "Los Mocks o Stubs aíslan la unidad probada, eliminando las dependencias que harían la prueba lenta o no determinista." },
  { "id": 227, "chapter": 3, "topic": "Revisiones Estáticas", "difficulty": "easy", "question": "¿Por qué las revisiones estáticas de requerimientos ahorran más dinero que las de código?", "options": [ "A) Porque leer es gratis.", "B) Porque un defecto en requerimientos propagado a diseño y luego a código multiplica el esfuerzo de re-trabajo necesario para arreglarlo.", "C) Porque los analistas cobran menos.", "D) Porque no usan ordenadores." ], "correctAnswer": 1, "explanation": "Siguiendo la regla de Shift-Left, evitar escribir mal el código es mucho más barato que escribirlo mal, probarlo mal, encontrar el error y volver a diseñarlo." },
  { "id": 228, "chapter": 4, "topic": "Caso de Prueba", "difficulty": "medium", "question": "¿Cuál es la diferencia entre un Caso de Prueba de 'Alto Nivel' y uno de 'Bajo Nivel'?", "options": [ "A) El de alto nivel lo aprueba el gerente, el de bajo el desarrollador.", "B) El de alto nivel es lógico/abstracto (sin valores exactos); el de bajo nivel tiene datos concretos ejecutables (ej. Usuario='Juan', Pass='1234').", "C) El de alto nivel es más seguro.", "D) Son sinónimos." ], "correctAnswer": 1, "explanation": "Alto Nivel (Abstract Test Case) define 'Probar con tarjeta rechazada'. Bajo Nivel (Concrete Test Case) define 'Probar con tarjeta VISA número 4000... exp 12/24'." },
  { "id": 229, "chapter": 5, "topic": "Configuración", "difficulty": "medium", "question": "Si al probar la versión v2.0 de la App reportas un defecto, pero el desarrollador dice 'A mí me funciona bien', el problema más probable es:", "options": [ "A) Falta de habilidades de programación.", "B) Una deficiente Gestión de la Configuración (el desarrollador puede estar mirando el código de la v2.1 y tú probaste la v1.9).", "C) Pruebas de estrés insuficientes.", "D) Falacia de ausencia de errores." ], "correctAnswer": 1, "explanation": "Sin un control de versiones estricto (tanto de código, bases de datos y entornos), es imposible reproducir defectos con consistencia." },
  { "id": 230, "chapter": 6, "topic": "Trazabilidad", "difficulty": "easy", "question": "¿Por qué las herramientas ALM proporcionan mejor trazabilidad que un Excel gigante?", "options": [ "A) Porque tienen colores.", "B) Porque las relaciones entre Requisitos, Pruebas y Defectos son hipervínculos bidireccionales dinámicos que se actualizan automáticamente.", "C) Porque son más caras.", "D) Porque no necesitan testers." ], "correctAnswer": 1, "explanation": "Las herramientas evitan el infierno de actualizar hojas de cálculo manuales. Si un requisito cambia de estado, la herramienta marca la prueba correspondiente como 'Por revisar'." },
  { "id": 231, "chapter": 1, "topic": "Principios", "difficulty": "medium", "question": "Creer que si arreglamos todos los bugs técnicos el sistema será un éxito de mercado, ¿qué principio ignora?", "options": [ "A) Agrupación de defectos.", "B) La falacia de la ausencia de errores (ausencia de defectos).", "C) Paradoja del pesticida.", "D) Shift-left." ], "correctAnswer": 1, "explanation": "Un producto puede no tener bugs pero ser totalmente inútil o frustrante para los usuarios. Arreglar defectos no garantiza el éxito si el requisito original era malo." },
  { "id": 232, "chapter": 2, "topic": "Regresión", "difficulty": "medium", "question": "¿Qué factor NO deberías priorizar al seleccionar casos para una suite de Regresión automatizada?", "options": [ "A) Riesgo e impacto comercial de las funciones principales.", "B) Casos de prueba que descubrieron muchos defectos en el pasado.", "C) Casos de prueba estables y repetibles.", "D) Pruebas Ad-hoc que cambian cada día." ], "correctAnswer": 3, "explanation": "La regresión necesita estabilidad. Las pruebas exploratorias o ad-hoc son manuales por naturaleza y demasiado frágiles o variables para automatizarlas eficientemente." },
  { "id": 233, "chapter": 3, "topic": "Tipos de Revisión", "difficulty": "hard", "question": "Si se envía por correo el documento de diseño a todo el equipo para que lo lean en sus ratos libres y dejen notas al margen, estamos ante:", "options": [ "A) Una Inspección formal.", "B) Un Walkthrough.", "C) Una Revisión Informal (Peer Review no estructurada).", "D) Pruebas Dinámicas." ], "correctAnswer": 2, "explanation": "No hay reuniones de consolidación, roles asignados ni kick-off, lo que la clasifica como una revisión informal de baja documentación." },
  { "id": 234, "chapter": 4, "topic": "Transición de Estado", "difficulty": "hard", "question": "Un cajero bloquea la tarjeta tras 3 PIN incorrectos. ¿Cuántas transiciones hay desde el estado 'Esperando PIN' al estado 'Validando PIN' si se permite reintentar?", "options": [ "A) 1", "B) 2", "C) 3", "D) Infinitas" ], "correctAnswer": 1, "explanation": "Generalmente, hay dos eventos desde 'Esperando': Ingresar PIN válido (1 transición al flujo feliz) e Ingresar PIN inválido (1 transición al bucle de reintento). El límite 3 detona una transición diferente hacia 'Bloqueado'." },
  { "id": 235, "chapter": 5, "topic": "Riesgo", "difficulty": "medium", "question": "¿Cómo se aplica el concepto de 'Pruebas Basadas en el Riesgo' en la ejecución de pruebas?", "options": [ "A) Las pruebas con mayor riesgo se ejecutan de primero.", "B) Las pruebas con mayor riesgo se dejan de último.", "C) Se omite la ejecución de pruebas de bajo riesgo por completo.", "D) Las pruebas se ejecutan en orden alfabético." ], "correctAnswer": 0, "explanation": "Priorizar el riesgo asegura que si se recorta el presupuesto o el tiempo, las áreas críticas de mayor impacto han sido probadas exhaustivamente." },
  { "id": 236, "chapter": 6, "topic": "Métricas", "difficulty": "easy", "question": "¿Qué proveen las herramientas (Dashboards) modernas a los gestores del proyecto?", "options": [ "A) Código fuente ofuscado.", "B) Transparencia y Visibilidad inmediata del estado de calidad y avance mediante gráficos y tablas consolidadas.", "C) Eliminación de los roles QA.", "D) Modelado 3D." ], "correctAnswer": 1, "explanation": "La telemetría del dashboard permite ver de un vistazo si la regresión falló, cuántos bugs severos hay abiertos y cuál es la cobertura de requisitos." },
  { "id": 237, "chapter": 1, "topic": "Trazabilidad", "difficulty": "hard", "question": "En auditorías reguladas (ej. software aeronáutico DO-178C), la trazabilidad hacia adelante (Forward Traceability) demuestra:", "options": [ "A) Qué desarrollador hizo cada bug.", "B) Que todos los requerimientos han sido probados (Req -> Caso de Prueba -> Resultado de Ejecución).", "C) Que el presupuesto no se excedió.", "D) Que el código no tiene funciones ocultas." ], "correctAnswer": 1, "explanation": "Rastrear de adelante hacia atrás asegura que no dejamos nada sin probar (cobertura total de requisitos)." },
  { "id": 238, "chapter": 2, "topic": "Modelos Ágiles", "difficulty": "hard", "question": "En un entorno de Integración Continua, si la suite de pruebas unitarias automatizadas falla en el servidor CI, ¿qué debe ocurrir inmediatamente?", "options": [ "A) El despliegue a producción debe continuar asumiendo que es un falso positivo.", "B) La 'Build' (compilación) se rechaza y se alerta a los desarrolladores para arreglar la integración rota.", "C) Se reinicia el servidor y se ignora el error.", "D) Se cambian los requerimientos." ], "correctAnswer": 1, "explanation": "El propósito del CI (Continuous Integration) es actuar como guardián. Si la build falla (las pruebas unitarias rompen), el código no se propaga a los demás ni a los entornos de pruebas." },
  { "id": 239, "chapter": 3, "topic": "Revisión", "difficulty": "medium", "question": "¿Qué técnica de diseño se utiliza MÁS para la revisión estática del propio código (encontrar posibles desbordamientos de buffer)?", "options": [ "A) Análisis Dinámico.", "B) Ejecutar Casos de Prueba de Particiones.", "C) Herramientas de Análisis de Flujo de Datos y Flujo de Control.", "D) Diagramas de Casos de Uso." ], "correctAnswer": 2, "explanation": "El flujo de datos (ver donde se declara y usa una variable) y el de control son las bases matemáticas que usan los analizadores estáticos para atrapar defectos estructurales de seguridad en el código." },
  { "id": 240, "chapter": 4, "topic": "Valores Límite", "difficulty": "hard", "question": "Un campo de fecha acepta años bisiestos. Probar el 29 de febrero del año 2000 es un ejemplo excelente de técnica de:", "options": [ "A) Transición de estado.", "B) Pruebas de estrés.", "C) Análisis de Valores Límite combinado con Adivinación de Errores.", "D) Pruebas unitarias." ], "correctAnswer": 2, "explanation": "Es un límite de negocio y matemático (29 de un mes que la mayoría de los años llega a 28, o división por múltiplos de 400), muy propenso a errores en sistemas obsoletos." }
];

data.push(...newQuestions);
fs.writeFileSync(questionsFile, JSON.stringify(data, null, 2));
console.log('Added ' + newQuestions.length + ' new questions. Total is now: ' + data.length);
