const fs = require('fs');

const questionsFile = './src/data/questions.json';
const data = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));

const newQuestions = [
  { "id": 136, "chapter": 4, "topic": "Caja Blanca", "difficulty": "medium", "question": "¿Qué métrica se utiliza en las pruebas de caja blanca para medir cuántas sentencias ejecutables se han probado?", "options": [ "A) Cobertura de Requisitos.", "B) Cobertura de Sentencias.", "C) Cobertura de Transición de Estado.", "D) Densidad de Defectos." ], "correctAnswer": 1, "explanation": "La cobertura de sentencias (Statement Coverage) calcula el porcentaje de líneas de código ejecutables que han sido transitadas por los casos de prueba." },
  { "id": 137, "chapter": 4, "topic": "Cobertura de Decisiones", "difficulty": "hard", "question": "Si alcanzas el 100% de cobertura de decisiones en una pieza de código, ¿qué otra cobertura técnica tienes garantizada al 100%?", "options": [ "A) Cobertura de Caminos Múltiples.", "B) Cobertura de Sentencias.", "C) Cobertura de Casos de Uso.", "D) Cobertura de Condiciones." ], "correctAnswer": 1, "explanation": "El 100% de cobertura de decisiones siempre garantiza el 100% de cobertura de sentencias. Pero no al revés." },
  { "id": 138, "chapter": 4, "topic": "Basadas en la Experiencia", "difficulty": "easy", "question": "¿Cuándo es más efectivo usar técnicas basadas en la experiencia (como la Exploratoria o Adivinación de Errores)?", "options": [ "A) Solo al inicio del proyecto.", "B) Como complemento a las técnicas formales de caja negra y caja blanca, o cuando no hay especificaciones escritas.", "C) Para reemplazar todas las pruebas formales y ahorrar dinero.", "D) Cuando los testers no tienen experiencia." ], "correctAnswer": 1, "explanation": "Estas técnicas no deben ser las únicas, pero son excelentes para encontrar bugs que las técnicas formales no atrapan, y brillan cuando la documentación es pobre." },
  { "id": 139, "chapter": 4, "topic": "Técnicas", "difficulty": "medium", "question": "Un tester diseña pruebas leyendo el código fuente Java del sistema. ¿Qué categoría de técnica está usando?", "options": [ "A) Caja Negra.", "B) Caja Blanca.", "C) Caja Gris.", "D) Basada en la Especificación." ], "correctAnswer": 1, "explanation": "Las técnicas que derivan pruebas a partir de la estructura interna o el código fuente son técnicas estructurales o de Caja Blanca." },
  { "id": 140, "chapter": 5, "topic": "Organización", "difficulty": "easy", "question": "En un equipo de pruebas maduro, ¿cuál es el nivel más bajo de independencia que puedes tener?", "options": [ "A) Probadores externos (Outsourcing).", "B) Probadores de otro departamento (ej. Seguridad).", "C) Desarrollador probando su propio código.", "D) Equipo de pruebas independiente dentro del mismo proyecto." ], "correctAnswer": 2, "explanation": "El desarrollador probando su propio código es el nivel 0 de independencia, ya que es la persona más sesgada hacia su trabajo." },
  { "id": 141, "chapter": 5, "topic": "Planificación", "difficulty": "medium", "question": "¿Qué documento de prueba describe las actividades, los recursos, el cronograma y el enfoque para todo un proyecto de pruebas?", "options": [ "A) Plan de Pruebas (Test Plan).", "B) Informe de Defectos.", "C) Especificación del Diseño de Pruebas.", "D) Plan de Proyecto Ágil." ], "correctAnswer": 0, "explanation": "El Plan de Pruebas proporciona la directriz logística y estratégica para ejecutar las pruebas en un proyecto o fase." },
  { "id": 142, "chapter": 5, "topic": "Estimación", "difficulty": "hard", "question": "La técnica 'Planning Poker' utilizada en entornos ágiles es una forma de estimación:", "options": [ "A) Basada en métricas.", "B) Basada en herramientas algorítmicas.", "C) Basada en expertos.", "D) Basada en riesgos." ], "correctAnswer": 2, "explanation": "Planning Poker junta a expertos (el equipo de desarrollo y QA) para discutir y llegar a un consenso sobre el esfuerzo de una tarea basada en su experiencia." },
  { "id": 143, "chapter": 5, "topic": "Control de Pruebas", "difficulty": "medium", "question": "Monitorear que el proyecto va según lo planeado e implementar medidas correctivas si hay desviaciones se conoce como:", "options": [ "A) Test Closure (Cierre de Pruebas).", "B) Test Design (Diseño de Pruebas).", "C) Test Control (Control de Pruebas).", "D) Test Review (Revisión de Pruebas)." ], "correctAnswer": 2, "explanation": "El Control de pruebas (Test Control) compara el progreso real con el planificado y toma acciones correctivas para guiar el proyecto de vuelta a su curso." },
  { "id": 144, "chapter": 5, "topic": "Gestión de Riesgos", "difficulty": "hard", "question": "¿Cuáles son los dos componentes que se utilizan para determinar el 'Nivel de Riesgo' (Risk Level)?", "options": [ "A) Dinero y Tiempo.", "B) Probabilidad de Ocurrencia e Impacto del Daño.", "C) Severidad y Prioridad.", "D) Tamaño del código y Complejidad." ], "correctAnswer": 1, "explanation": "El Nivel de Riesgo se calcula multiplicando la Probabilidad (qué tan probable es que ocurra) por el Impacto (cuánto daño hará si ocurre)." },
  { "id": 145, "chapter": 5, "topic": "Reporte de Incidentes", "difficulty": "easy", "question": "Un buen reporte de defectos (Bug Report) debe permitir a los desarrolladores:", "options": [ "A) Saber a quién culpar.", "B) Ignorar el problema si no tienen tiempo.", "C) Reproducir, entender y corregir el defecto de forma eficiente.", "D) Aumentar la métrica de defectos falsos positivos." ], "correctAnswer": 2, "explanation": "Un reporte claro (con pasos de reproducción, resultado esperado y resultado real) es crucial para que el desarrollador aisle el fallo." },
  { "id": 146, "chapter": 6, "topic": "Herramientas", "difficulty": "medium", "question": "¿Qué tipo de herramienta ejecutaría scripts de prueba en las noches sin intervención humana (Continuous Integration)?", "options": [ "A) Herramientas de preparación de datos.", "B) Herramientas de ejecución de pruebas.", "C) Analizadores estáticos.", "D) Herramientas de modelado UML." ], "correctAnswer": 1, "explanation": "Las herramientas de ejecución interactúan con la aplicación inyectando acciones (clicks, teclados) de forma automatizada (ej. Selenium, Cypress)." },
  { "id": 147, "chapter": 6, "topic": "Rendimiento", "difficulty": "medium", "question": "¿Qué simulan las herramientas de pruebas de rendimiento/carga (ej. JMeter)?", "options": [ "A) Entornos de red desconectados.", "B) Un número masivo de usuarios concurrentes (carga virtual) interactuando con el sistema.", "C) Pruebas de usabilidad gráfica.", "D) Compilaciones en múltiples sistemas operativos." ], "correctAnswer": 1, "explanation": "Generan carga sintética para estresar servidores y bases de datos, simulando miles de peticiones simultáneas." },
  { "id": 148, "chapter": 6, "topic": "Herramientas", "difficulty": "easy", "question": "¿Qué herramienta usarías para crear una matriz de trazabilidad entre requisitos y casos de prueba?", "options": [ "A) Herramienta de gestión de requisitos o gestión de pruebas (ALM).", "B) Herramienta de cobertura de código.", "C) Compilador de C++.", "D) Herramienta de monitorización de red." ], "correctAnswer": 0, "explanation": "Las herramientas de gestión de pruebas (ej. Jira con Xray, TestRail) permiten vincular (trazar) los tickets de historias de usuario a sus respectivas pruebas." },
  { "id": 149, "chapter": 6, "topic": "Prueba de Concepto", "difficulty": "medium", "question": "Al adquirir una herramienta nueva, la 'Prueba de Concepto (PoC)' ayuda a:", "options": [ "A) Decidir la estructura jerárquica de la empresa.", "B) Verificar que la herramienta es compatible con la tecnología real del proyecto antes de comprar la licencia definitiva.", "C) Escribir el plan de pruebas del proyecto.", "D) Obtener la certificación ISTQB." ], "correctAnswer": 1, "explanation": "Una PoC evalúa la herramienta bajo fuego real en una parte pequeña del código para asegurar que funciona y no fue solo marketing de ventas." },
  { "id": 150, "chapter": 1, "topic": "Calidad", "difficulty": "medium", "question": "¿Cómo contribuyen las pruebas al aseguramiento de la calidad (QA)?", "options": [ "A) Al reemplazar la necesidad de QA.", "B) Las pruebas (QC) miden la calidad del producto y reportan fallos, lo que QA usa para mejorar los procesos y evitar futuros defectos.", "C) Las pruebas son exactamente lo mismo que el aseguramiento de calidad.", "D) QA solo se encarga de probar interfaces gráficas." ], "correctAnswer": 1, "explanation": "QA se centra en el PROCESO, mientras que el Testing se centra en el PRODUCTO. Las pruebas proporcionan la retroalimentación que QA utiliza para optimizar procesos." },
  { "id": 151, "chapter": 1, "topic": "Psicología", "difficulty": "easy", "question": "Un desarrollador y un tester pueden tener conflictos porque:", "options": [ "A) Los testers cobran más que los desarrolladores.", "B) Tienen mentalidades diferentes: el desarrollador construye (mentalidad constructiva) y el tester critica/rompe (mentalidad destructiva analítica).", "C) Las herramientas de prueba siempre corrompen el código fuente.", "D) Ambos roles realizan exactamente el mismo trabajo." ], "correctAnswer": 1, "explanation": "La fricción surge de la diferencia de mentalidades, lo que hace que la comunicación diplomática sea la habilidad principal de un tester." },
  { "id": 152, "chapter": 2, "topic": "Modelo Cascada", "difficulty": "medium", "question": "¿Cuál es un inconveniente grave de hacer pruebas en un modelo de ciclo de vida secuencial puro (Cascada)?", "options": [ "A) Cuesta muy poco.", "B) Los defectos de los requisitos no se detectan hasta las pruebas del sistema o aceptación, cuando arreglarlos es muy caro.", "C) Exige demasiadas automatizaciones.", "D) No requiere documentación." ], "correctAnswer": 1, "explanation": "Como las pruebas ocurren al final, si el análisis inicial estaba mal, el sistema entero estará mal y habrá que reconstruirlo casi desde cero." },
  { "id": 153, "chapter": 2, "topic": "Tipos de Prueba", "difficulty": "medium", "question": "¿Las pruebas de regresión solo se aplican en la fase de mantenimiento?", "options": [ "A) Sí, nunca antes del lanzamiento a producción.", "B) No, deben ejecutarse en cualquier momento (en cualquier nivel de prueba) donde se modifique o parchee el software.", "C) Sí, porque en desarrollo no hay regresiones.", "D) Solo las ejecuta el usuario final." ], "correctAnswer": 1, "explanation": "Cada vez que se modifica código, ya sea arreglando un defecto en pruebas de componente o añadiendo una función en sistema, se debe hacer regresión." },
  { "id": 154, "chapter": 3, "topic": "Métricas Estáticas", "difficulty": "medium", "question": "¿Qué métrica es útil para evaluar la eficiencia de un proceso de revisión?", "options": [ "A) El número de sentencias IF en el código.", "B) Defectos encontrados por página u hora, y el coste estimado ahorrado al no encontrarlos en producción.", "C) La cantidad de café consumida.", "D) El número de testers contratados." ], "correctAnswer": 1, "explanation": "Las métricas de revisión se basan en el esfuerzo (tiempo invertido) frente al valor obtenido (defectos críticos encontrados tempranamente)." },
  { "id": 155, "chapter": 3, "topic": "Herramientas", "difficulty": "easy", "question": "¿Un compilador de Java realiza análisis estático?", "options": [ "A) Sí, detecta errores de sintaxis y tipos sin ejecutar la aplicación.", "B) No, solo compila.", "C) Sí, pero solo detecta problemas de rendimiento web.", "D) No, es una herramienta dinámica." ], "correctAnswer": 0, "explanation": "Los compiladores e IDEs son la primera línea de herramientas de análisis estático, encontrando fallas evidentes de sintaxis antes de la ejecución." },
  { "id": 156, "chapter": 4, "topic": "Tabla de Decisión", "difficulty": "hard", "question": "En una tabla de decisión, ¿qué sucede cuando se combinan o colapsan dos columnas?", "options": [ "A) El sistema crashea.", "B) Significa que el resultado de la Acción es el mismo sin importar el valor de una de las Condiciones.", "C) Se añade una nueva Condición.", "D) Se divide por cero." ], "correctAnswer": 1, "explanation": "Colapsar o reducir reglas ocurre cuando una condición específica se vuelve irrelevante ('No importa' / Don't Care) para activar una acción concreta." },
  { "id": 157, "chapter": 4, "topic": "Transición de Estado", "difficulty": "hard", "question": "¿Qué cobertura mide el porcentaje de todas las combinaciones posibles de transiciones de dos pasos sucesivos?", "options": [ "A) Cobertura de todos los estados.", "B) Cobertura de transiciones válidas.", "C) Cobertura de pares de transiciones (0-switch, 1-switch).", "D) Cobertura de sentencias." ], "correctAnswer": 2, "explanation": "La cobertura de pares de transiciones asegura probar secuencias específicas de eventos, ej. Evento A seguido inmediatamente del Evento B." },
  { "id": 158, "chapter": 5, "topic": "Criterios", "difficulty": "easy", "question": "Si el cliente cambia de idea a mitad del proyecto y exige una característica no planeada, ¿esto afecta al Plan de Pruebas?", "options": [ "A) No, el plan no se puede cambiar.", "B) Sí, esto es un Riesgo de Proyecto (Alcance Creep) y requiere actualizar el Plan y la Estimación.", "C) No, los probadores lo probarán gratis.", "D) Sí, pero no afecta al presupuesto." ], "correctAnswer": 1, "explanation": "Los cambios de alcance (Scope Creep) modifican los requerimientos y obligan a reevaluar la planificación, tiempos y riesgos del proyecto." },
  { "id": 159, "chapter": 5, "topic": "Prioridad vs Severidad", "difficulty": "medium", "question": "Un fallo impide iniciar sesión a todos los usuarios, pero se ha encontrado un método alternativo (workaround) y afecta a pocos porque están de vacaciones. ¿Cuál es su categorización ideal?", "options": [ "A) Severidad Crítica, Prioridad Alta.", "B) Severidad Crítica, Prioridad Media/Baja.", "C) Severidad Baja, Prioridad Alta.", "D) Severidad Baja, Prioridad Baja." ], "correctAnswer": 1, "explanation": "La Severidad es Crítica porque la funcionalidad base (Login) está totalmente rota técnicamente. La Prioridad puede bajar a Media si hay un workaround y no hay usuarios activos afectados urgentemente." },
  { "id": 160, "chapter": 6, "topic": "Herramientas de Diseño", "difficulty": "medium", "question": "¿Qué tipo de herramienta ayuda a generar casos de prueba automáticamente a partir de un modelo conceptual o matemático del sistema?", "options": [ "A) Herramientas Model-Based Testing (Pruebas basadas en modelos).", "B) Herramientas de seguimiento de incidentes.", "C) Herramientas de preparación de datos.", "D) Generadores de HTML." ], "correctAnswer": 0, "explanation": "El Model-Based Testing (MBT) automatiza el diseño de casos de prueba leyendo diagramas de estado, flujos o máquinas lógicas." },
  { "id": 161, "chapter": 1, "topic": "Aseguramiento", "difficulty": "medium", "question": "¿Es posible realizar pruebas exhaustivas (probar todas las entradas posibles)?", "options": [ "A) Sí, si tienes suficientes testers.", "B) Sí, mediante automatización masiva.", "C) No, es imposible a menos que el software sea trivial. Es uno de los principios de las pruebas.", "D) Sí, es un requisito legal." ], "correctAnswer": 2, "explanation": "El principio 2 de ISTQB dice que las Pruebas Exhaustivas son imposibles debido a las combinaciones infinitas de entradas y precondiciones, por lo que usamos el enfoque de Riesgos." },
  { "id": 162, "chapter": 2, "topic": "Tipos de Prueba", "difficulty": "hard", "question": "Un probador ejecuta una base de datos para comprobar si maneja correctamente caracteres asiáticos. Esto se clasifica principalmente como:", "options": [ "A) Prueba funcional (Internacionalización/Localización).", "B) Prueba estructural.", "C) Prueba de rendimiento.", "D) Prueba de componente." ], "correctAnswer": 0, "explanation": "Verificar soporte multi-idioma (I18N/L10N) es una prueba funcional orientada a las especificaciones de comportamiento del mercado." },
  { "id": 163, "chapter": 3, "topic": "Análisis Estático", "difficulty": "medium", "question": "¿Qué tipo de defectos es MENOS probable que encuentre el Análisis Estático automático?", "options": [ "A) Variables no inicializadas.", "B) Código inalcanzable (Dead Code).", "C) Errores en la lógica de negocio donde el programador malinterpretó el requerimiento.", "D) Violaciones de convenciones de nomenclatura." ], "correctAnswer": 2, "explanation": "Las herramientas estáticas no entienden el 'negocio' ni la intención humana; solo encuentran errores sintácticos, estructurales o arquitectónicos." },
  { "id": 164, "chapter": 4, "topic": "Adivinación de Errores", "difficulty": "easy", "question": "¿Por qué un probador buscaría un defecto al ingresar un '0' en un campo de división?", "options": [ "A) Porque lo leyó en el código (Caja Blanca).", "B) Por la técnica de Adivinación de Errores basada en experiencia previa (división por cero).", "C) Porque es una técnica de Transición de Estado.", "D) Porque se lo indicó el gestor del proyecto." ], "correctAnswer": 1, "explanation": "La división por cero es uno de los fallos clásicos (junto con los punteros nulos o las fechas del 29 de febrero) que los testers expertos siempre atacan." },
  { "id": 165, "chapter": 5, "topic": "Métricas", "difficulty": "medium", "question": "¿Qué indica una alta 'Tasa de Fuga de Defectos' (Defect Leakage) hacia el cliente?", "options": [ "A) Que el equipo de pruebas hizo un excelente trabajo.", "B) Que las pruebas fueron insuficientes o ineficaces y los defectos escaparon a producción.", "C) Que el sistema es invulnerable.", "D) Que el cliente es muy quisquilloso." ], "correctAnswer": 1, "explanation": "La fuga de defectos mide los bugs que el equipo de QA no encontró pero que los usuarios finales sí. Una alta fuga implica procesos deficientes." },
  { "id": 166, "chapter": 6, "topic": "Keyword-Driven", "difficulty": "hard", "question": "En la automatización Keyword-Driven, las 'palabras clave' (keywords) representan:", "options": [ "A) Consultas SQL exclusivas.", "B) Acciones lógicas o pasos de negocio (ej. 'Login_Usuario', 'Añadir_Al_Carro') sin código complejo visible.", "C) El nombre de los testers.", "D) Contraseñas de bases de datos." ], "correctAnswer": 1, "explanation": "Las keywords abstraen las interacciones complejas de la interfaz gráfica a un idioma casi natural que los probadores de negocio pueden usar para construir pruebas." },
  { "id": 167, "chapter": 1, "topic": "Conceptos", "difficulty": "medium", "question": "¿Qué actividad implica evaluar la calidad y buscar defectos sin ejecutar el código?", "options": [ "A) QA Testing.", "B) Testing Dinámico.", "C) Testing Estático.", "D) UAT Testing." ], "correctAnswer": 2, "explanation": "Las pruebas estáticas (revisiones, análisis de código) se caracterizan porque la aplicación no está en estado de ejecución." },
  { "id": 168, "chapter": 2, "topic": "Mantenimiento", "difficulty": "easy", "question": "¿Se pueden usar herramientas de automatización de Regresión en las Pruebas de Mantenimiento?", "options": [ "A) No, están prohibidas.", "B) Sí, de hecho son la herramienta ideal para garantizar que los sistemas legados no se rompan por un parche.", "C) Solo si se cambia de lenguaje de programación.", "D) Nunca." ], "correctAnswer": 1, "explanation": "Dado que el mantenimiento suele implicar pequeños cambios en grandes sistemas, una suite de regresión automatizada es la mejor defensa." },
  { "id": 169, "chapter": 3, "topic": "Inspecciones", "difficulty": "hard", "question": "En las inspecciones formales, la métrica principal suele recolectarse durante la fase de:", "options": [ "A) Planificación.", "B) Preparación individual y Reunión de Revisión.", "C) Solo después del lanzamiento.", "D) Kick-off." ], "correctAnswer": 1, "explanation": "Los defectos se identifican mayormente durante el estudio individual y se consolidan en la reunión de revisión formal (logging meeting)." },
  { "id": 170, "chapter": 4, "topic": "Pruebas Exploratorias", "difficulty": "medium", "question": "En el contexto de Pruebas Exploratorias, ¿qué es un 'Test Charter' (Carta de Prueba)?", "options": [ "A) Un documento que te certifica como tester.", "B) La declaración del objetivo a explorar (ej. 'Explorar la pasarela de pagos para buscar fallos de concurrencia').", "C) Un ticket de soporte.", "D) Un comando de consola." ], "correctAnswer": 1, "explanation": "Las cartas guían y acotan las sesiones de prueba exploratoria para que no pierdan foco (Session-Based Test Management)." }
];

data.push(...newQuestions);
fs.writeFileSync(questionsFile, JSON.stringify(data, null, 2));
console.log('Added ' + newQuestions.length + ' new questions. Total is now: ' + data.length);
