const fs = require('fs');

const questionsFile = './src/data/questions.json';
const data = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));

const newQuestions = [
  { "id": 171, "chapter": 1, "topic": "Psicología", "difficulty": "hard", "question": "¿Qué sesgo cognitivo hace que un desarrollador crea que su código no tiene errores porque fue él quien lo escribió?", "options": [ "A) Sesgo de Confirmación.", "B) Agrupación de Defectos.", "C) Paradoja del Pesticida.", "D) Ilusión de control." ], "correctAnswer": 0, "explanation": "El sesgo de confirmación hace que el cerebro busque evidencia que confirme sus creencias ('mi código funciona') y minimice la información contradictoria ('ese bug es un caso extremo')." },
  { "id": 172, "chapter": 2, "topic": "Modelos Ágiles", "difficulty": "medium", "question": "En Agile, ¿cuál es el nivel de prueba más asociado con el 'Test-Driven Development' (TDD)?", "options": [ "A) Pruebas de Aceptación.", "B) Pruebas de Sistema.", "C) Pruebas de Componente (Unitarias).", "D) Pruebas de Usabilidad." ], "correctAnswer": 2, "explanation": "El TDD es una práctica técnica donde los desarrolladores escriben primero una prueba unitaria que falla, y luego escriben el código de componente para pasarla." },
  { "id": 173, "chapter": 3, "topic": "Análisis Estático", "difficulty": "hard", "question": "El Análisis Estático suele calcular una métrica que advierte sobre código difícil de mantener o probar. ¿Cuál es?", "options": [ "A) Cobertura de Sentencias.", "B) Complejidad Ciclomática.", "C) Defectos Encontrados.", "D) Densidad de Bugs." ], "correctAnswer": 1, "explanation": "La complejidad ciclomática mide el número de caminos independientes por la estructura de control del código. Valores altos indican código espagueti." },
  { "id": 174, "chapter": 4, "topic": "Caja Negra vs Blanca", "difficulty": "medium", "question": "¿Las técnicas de caja blanca son exclusivas de las pruebas unitarias?", "options": [ "A) Sí, porque a nivel de sistema no hay código visible.", "B) No, se pueden usar en pruebas de integración, sistema o incluso a nivel de arquitectura general (ej. cobertura de menús).", "C) Sí, porque es el único entorno con analizadores de código.", "D) Nunca se pueden usar en integración." ], "correctAnswer": 1, "explanation": "Aunque es más común a nivel unitario, el análisis estructural de caja blanca se puede aplicar a diagramas de llamadas a nivel de integración o de sistema." },
  { "id": 175, "chapter": 5, "topic": "Planificación", "difficulty": "medium", "question": "¿Qué documento de la gestión de pruebas describe *CÓMO* se aplicará el enfoque para un tipo o nivel específico de pruebas, pero no su cronograma?", "options": [ "A) Master Test Plan.", "B) Estrategia de Pruebas (Test Strategy).", "C) Resumen de Ejecución.", "D) Defect Report." ], "correctAnswer": 1, "explanation": "La estrategia describe el enfoque genérico (métodos, técnicas, automatización). El plan define el *CÚANDO* y el *QUIÉN*." },
  { "id": 176, "chapter": 6, "topic": "Rendimiento", "difficulty": "easy", "question": "Diferencia principal entre Pruebas de Carga y Pruebas de Estrés:", "options": [ "A) Las de estrés rompen el sistema a propósito.", "B) Las de carga evalúan el sistema bajo el límite normal esperado; las de estrés superan ampliamente esos límites hasta que el sistema falla para ver su comportamiento.", "C) Las de carga son funcionales y las de estrés estructurales.", "D) No hay diferencia." ], "correctAnswer": 1, "explanation": "El estrés busca encontrar el punto exacto de ruptura y evaluar cómo el sistema se recupera del fallo masivo." },
  { "id": 177, "chapter": 1, "topic": "Roles", "difficulty": "easy", "question": "¿Es obligatorio que un equipo Scrum tenga un 'Tester' especializado?", "options": [ "A) Sí, Scrum exige los roles de Tester y Desarrollador.", "B) No, el framework Scrum solo reconoce el rol de 'Desarrollador' dentro del equipo, aunque ese desarrollador pueda ser un especialista en QA.", "C) Sí, es un requisito legal.", "D) Nunca debe haber testers en Scrum." ], "correctAnswer": 1, "explanation": "Scrum Guide no tiene sub-roles. Todos son Developers (desarrolladores del producto), aunque tengan habilidades especializadas como testing." },
  { "id": 178, "chapter": 2, "topic": "Mantenimiento", "difficulty": "medium", "question": "Al retirar un software antiguo (Retirement), ¿qué tipo de prueba es crucial?", "options": [ "A) UAT del antiguo sistema.", "B) Pruebas de Rendimiento.", "C) Pruebas de Mantenimiento centradas en la correcta migración y preservación de los datos históricos.", "D) Pruebas Unitarias del sistema obsoleto." ], "correctAnswer": 2, "explanation": "Cuando se retira un sistema, el mayor riesgo es perder datos históricos legales o romper la compatibilidad con otros sistemas que dependían de él." },
  { "id": 179, "chapter": 3, "topic": "Revisión", "difficulty": "easy", "question": "¿Un caso de prueba ya diseñado puede someterse a una revisión estática?", "options": [ "A) Sí, las especificaciones de prueba son documentos que deben y pueden ser revisados (ej. peer review) antes de la ejecución.", "B) No, los casos de prueba son la revisión en sí.", "C) Solo si están en formato PDF.", "D) Nunca, es una pérdida de tiempo." ], "correctAnswer": 0, "explanation": "Cualquier artefacto de software (código, manuales, requisitos, e incluso los mismos casos de prueba) se beneficia de ser revisado tempranamente." },
  { "id": 180, "chapter": 4, "topic": "Transición de Estado", "difficulty": "medium", "question": "¿Qué tabla acompaña frecuentemente al diagrama de transición de estado para mostrar todas las posibles transiciones (válidas e inválidas)?", "options": [ "A) Tabla de Decisión.", "B) Tabla de Estado (State Table).", "C) Matriz de Trazabilidad.", "D) Matriz RAM." ], "correctAnswer": 1, "explanation": "La tabla de estados lista el estado actual en las filas y los eventos en las columnas. Es crucial porque, a diferencia del diagrama, expone fácilmente las transiciones inválidas (eventos que no deberían hacer nada)." },
  { "id": 181, "chapter": 5, "topic": "Métricas", "difficulty": "medium", "question": "Si tu tasa de ejecución de pruebas es del 100%, ¿has terminado el proyecto con éxito?", "options": [ "A) Sí, no hay nada más que hacer.", "B) No necesariamente; si la tasa de fallo de esos casos es alta (muchos bugs abiertos), los criterios de salida de calidad pueden no cumplirse.", "C) Sí, el cliente siempre acepta el 100%.", "D) No, debes llegar al 200%." ], "correctAnswer": 1, "explanation": "Ejecutar todo no implica que todo funcione. El estado de los defectos descubiertos dictará si el producto es lanzable o no." },
  { "id": 182, "chapter": 6, "topic": "Herramientas de Ejecución", "difficulty": "hard", "question": "¿Cuál es un enfoque típico para mantener automatizaciones de interfaz gráfica (UI)?", "options": [ "A) Re-grabar scripts todos los días (Capture/Replay).", "B) Escribir las pruebas a bajo nivel dentro del código de producción.", "C) Utilizar Patrones de Diseño como Page Object Model (POM) para separar los selectores de UI de la lógica de prueba.", "D) Usar solo expresiones regulares." ], "correctAnswer": 2, "explanation": "El patrón POM asegura que si un botón cambia de nombre, solo modificas una clase de la página y todos los casos de prueba que lo usan seguirán funcionando." },
  { "id": 183, "chapter": 1, "topic": "Objetivos", "difficulty": "medium", "question": "¿Cuál es la diferencia entre Debugging (Depuración) y Testing (Pruebas)?", "options": [ "A) Son lo mismo.", "B) El tester realiza el debugging; el desarrollador el testing.", "C) El Testing revela la falla (failure); el Debugging encuentra, analiza y corrige la causa raíz (defecto) en el código.", "D) El Debugging es solo para interfaces gráficas." ], "correctAnswer": 2, "explanation": "Testing se centra en demostrar la existencia de errores o validar requerimientos. Depurar es la actividad técnica de programación para extirpar el bug." },
  { "id": 184, "chapter": 2, "topic": "Aceptación", "difficulty": "hard", "question": "¿Qué es la Prueba de Aceptación Operacional (OAT)?", "options": [ "A) Una prueba hecha por los usuarios comerciales.", "B) Una prueba realizada por los administradores de sistemas para comprobar copias de seguridad, restauración, y gestión de parches.", "C) Una prueba de usabilidad visual.", "D) Una prueba estática." ], "correctAnswer": 1, "explanation": "OAT es validación para el departamento de IT u operaciones, asegurando que pueden mantener el sistema productivo, restaurar datos y configurar redes sin fallos." },
  { "id": 185, "chapter": 3, "topic": "Inspecciones", "difficulty": "medium", "question": "¿Quién NO debería ser el moderador de una inspección formal?", "options": [ "A) Un probador experimentado.", "B) Un gerente técnico.", "C) El Autor del documento que se está revisando.", "D) Un ingeniero de procesos." ], "correctAnswer": 2, "explanation": "El autor no debe moderar porque está sesgado, podría ponerse a la defensiva o imponer su ritmo, arruinando la objetividad de la inspección." },
  { "id": 186, "chapter": 4, "topic": "Valores Límite", "difficulty": "easy", "question": "Un campo acepta contraseñas de 8 a 12 caracteres. Con BVA de 2 valores, ¿qué longitudes pruebas para el límite inferior?", "options": [ "A) 7, 8", "B) 8, 9", "C) 7, 8, 9", "D) 8, 12" ], "correctAnswer": 0, "explanation": "El límite es 8. Sus dos valores fronterizos son el límite mismo (8, válido) y justo por fuera del límite (7, inválido)." },
  { "id": 187, "chapter": 5, "topic": "Estimación", "difficulty": "hard", "question": "¿Cómo interviene la técnica 'Test Point Analysis' (TPA)?", "options": [ "A) Cuenta el número de probadores.", "B) Estima el esfuerzo de pruebas basándose en el análisis de Puntos de Función (Function Points) del software.", "C) Mide los puntos ciegos del código.", "D) Analiza el presupuesto consumido." ], "correctAnswer": 1, "explanation": "El Análisis de Puntos de Prueba (TPA) es una extensión paramétrica del análisis de puntos de función para derivar horas estimadas de prueba." },
  { "id": 188, "chapter": 6, "topic": "Herramientas de Gestión", "difficulty": "medium", "question": "En un ciclo Agile/Scrum maduro, una herramienta ALM (Application Lifecycle Management) sirve principalmente para:", "options": [ "A) Escribir el código fuente.", "B) Integrar requerimientos (Historias de Usuario), scripts de prueba, reportes de bugs y código fuente en una sola traza lógica.", "C) Analizar vulnerabilidades de red.", "D) Simular estrés." ], "correctAnswer": 1, "explanation": "Las ALMs proporcionan una única fuente de verdad para rastrear de un extremo a otro, permitiendo visibilidad en tiempo real a todo el equipo." },
  { "id": 189, "chapter": 1, "topic": "Contexto", "difficulty": "medium", "question": "El proyecto A es un sistema de e-commerce web. El proyecto B es el control de un marcapasos. Según ISTQB:", "options": [ "A) Se usarán las mismas herramientas.", "B) Se usarán las mismas técnicas.", "C) Las pruebas dependen del contexto: el B requerirá mucho más rigor, pruebas de seguridad y cobertura estructural obligatoria por ley.", "D) Ninguno requiere automatización." ], "correctAnswer": 2, "explanation": "Context is king. El contexto normativo, de seguridad (Safety) y regulatorio dicta el rigor del testing." },
  { "id": 190, "chapter": 2, "topic": "Testing Ágil", "difficulty": "medium", "question": "En el desarrollo Iterativo (ej. Scrum), ¿qué nivel de prueba tiende a desaparecer como una fase formal y masiva al final?", "options": [ "A) Pruebas de unidad.", "B) Pruebas de Integración Continua.", "C) Las Pruebas de Sistema separadas como un evento monolítico y largo antes de producción.", "D) El desarrollo dirigido por comportamiento (BDD)." ], "correctAnswer": 2, "explanation": "En ágil, las pruebas de sistema se dividen e integran constantemente al final de cada mini-ciclo de 2 semanas, en lugar de meses después." },
  { "id": 191, "chapter": 3, "topic": "Revisión Técnica", "difficulty": "hard", "question": "¿Cuál de estas NO suele ser una meta de la Revisión Técnica?", "options": [ "A) Evaluar alternativas técnicas de arquitectura.", "B) Encontrar defectos tempranos.", "C) Firmar contratos con terceros.", "D) Asegurar conformidad con estándares técnicos." ], "correctAnswer": 2, "explanation": "Las revisiones técnicas abordan el diseño de bases de datos, APIs o arquitecturas por pares de ingeniería, no asuntos legales ni contractuales." },
  { "id": 192, "chapter": 4, "topic": "Casos de Uso", "difficulty": "medium", "question": "¿A qué se asocia un 'Flujo Alternativo' en un caso de uso?", "options": [ "A) Al Main Success Scenario (El camino feliz).", "B) A excepciones o decisiones que se desvían del flujo principal pero aún permiten completar el objetivo o gestionar un error adecuadamente.", "C) A un servidor de respaldo.", "D) Al cierre de sesión forzoso." ], "correctAnswer": 1, "explanation": "Un flujo alternativo cubre casos como 'Tarjeta de crédito denegada' o 'Ruta alternativa elegida por el usuario' durante una transacción." },
  { "id": 193, "chapter": 5, "topic": "Gestión de Riesgos", "difficulty": "medium", "question": "Un tester sugiere cambiar el alcance de las pruebas debido a que hay un 80% de probabilidad de que el servidor de bases de datos colapse en el Black Friday. Esto es gestionar un Riesgo de:", "options": [ "A) Proyecto.", "B) Calidad.", "C) Producto (Desempeño/Rendimiento).", "D) Mercado." ], "correctAnswer": 2, "explanation": "La caída de un servidor debido a sobrecarga es un fallo del producto final, es decir, un riesgo de calidad o producto." },
  { "id": 194, "chapter": 6, "topic": "Herramientas de Análisis", "difficulty": "hard", "question": "¿Una herramienta de Análisis Dinámico puede ser utilizada para encontrar Memory Leaks (Fugas de memoria) en una aplicación C++?", "options": [ "A) Sí, las herramientas de análisis dinámico instrumentan la memoria mientras la aplicación se ejecuta.", "B) No, solo el análisis estático puede ver la memoria.", "C) Las fugas de memoria no existen en C++.", "D) Solo con herramientas manuales." ], "correctAnswer": 0, "explanation": "El análisis dinámico requiere que el código se ejecute; son las herramientas por excelencia para rastrear cómo el programa maneja el hardware, hilos y memoria en tiempo real." },
  { "id": 195, "chapter": 1, "topic": "Control de Calidad", "difficulty": "easy", "question": "¿Qué relación hay entre Testing y QC (Control de Calidad)?", "options": [ "A) Son enemigos mortales.", "B) Testing es una actividad que forma parte del Control de Calidad (QC) para encontrar defectos.", "C) Testing diseña procesos, QC los ejecuta.", "D) No tienen ninguna relación." ], "correctAnswer": 1, "explanation": "QC es el sistema de validación del producto terminado, y las Pruebas de Software son la herramienta operativa principal de ese QC." },
  { "id": 196, "chapter": 2, "topic": "DevOps", "difficulty": "medium", "question": "En un contexto CI/CD (DevOps), ¿cuándo se ejecutan típicamente las pruebas automatizadas de regresión y componente?", "options": [ "A) Una vez al mes.", "B) De forma automática cada vez que un desarrollador integra su código al repositorio principal (Commit/Push).", "C) Solo en producción.", "D) Después de la firma del contrato." ], "correctAnswer": 1, "explanation": "El pipeline de Integración Continua dispara suites de pruebas automáticas en minutos para validar que los últimos cambios no hayan roto la build." },
  { "id": 197, "chapter": 3, "topic": "Lista de Comprobación", "difficulty": "easy", "question": "¿Para qué se usa un Checklist (Lista de comprobación) durante una revisión estática?", "options": [ "A) Para recordar comprar café.", "B) Para guiar al revisor y asegurar que busque sistemáticamente errores comunes o violaciones de estándares que suelen omitirse.", "C) Como factura de horas trabajadas.", "D) Solo en revisiones informales." ], "correctAnswer": 1, "explanation": "Una lista de comprobación ayuda a centrar la revisión en defectos conocidos: ej. '¿Todos los bucles tienen fin?', '¿Las variables están tipadas?'." },
  { "id": 198, "chapter": 4, "topic": "Partición", "difficulty": "medium", "question": "En una pantalla de registro se debe ingresar una letra mayúscula (A-Z). Particiones: Inválida menor (0-9/Símbolos), Válida (A-Z), Inválida mayor (a-z). Selecciona representantes válidos:", "options": [ "A) 'A', 'M', 'Z'", "B) '1', 'a', '@'", "C) 'b', 'Z', 3", "D) '100', '200'" ], "correctAnswer": 0, "explanation": "Para la clase válida (A-Z), cualquier mayúscula sirve, como A, M o Z." },
  { "id": 199, "chapter": 5, "topic": "Riesgo", "difficulty": "medium", "question": "Contratar un seguro que cubra penalizaciones legales en caso de que el software financiero falle en producción, es una estrategia de:", "options": [ "A) Mitigación de riesgos de producto mediante pruebas.", "B) Transferencia de riesgo o Contingencia (Aceptación del Riesgo Residual).", "C) Análisis de valores límite.", "D) Prevención de defectos." ], "correctAnswer": 1, "explanation": "El riesgo no se elimina (el software puede seguir fallando), pero el daño económico (impacto) se ha transferido al seguro (Mitigación financiera, no técnica)." },
  { "id": 200, "chapter": 6, "topic": "Selección de Herramientas", "difficulty": "easy", "question": "¿Qué factor es el más importante al evaluar si una herramienta open-source es adecuada para tu empresa?", "options": [ "A) Que tenga iconos bonitos.", "B) La actividad de la comunidad, actualizaciones recientes y la capacidad del equipo interno para programar y mantenerla sin soporte comercial.", "C) Que cueste más de 1000$.", "D) Que no permita programar." ], "correctAnswer": 1, "explanation": "Las herramientas open-source (como Selenium) son gratis pero el coste real está en la formación y mantenimiento interno, ya que no hay un proveedor corporativo detrás." },
  { "id": 201, "chapter": 1, "topic": "Causas de Defectos", "difficulty": "medium", "question": "La fatiga del desarrollador, plazos ajustados y mala comunicación. ¿A qué corresponden estos conceptos?", "options": [ "A) Son los fallos del sistema.", "B) Son las causas raíces típicas que provocan que los humanos cometan errores (mistakes) en el software.", "C) Son defectos estructurales.", "D) Son métricas de cobertura." ], "correctAnswer": 1, "explanation": "La presión del tiempo, ambientes ruidosos o falta de conocimientos son los causantes directos de los errores humanos en el desarrollo." },
  { "id": 202, "chapter": 2, "topic": "Pruebas Alpha y Beta", "difficulty": "hard", "question": "En el contexto de software comercial COTS (Off-the-shelf), las Pruebas Beta se caracterizan porque:", "options": [ "A) Se simulan con robots.", "B) Las ejecutan probadores internos.", "C) Se envían a un grupo selecto del mercado real para probarlo de forma libre en sus propios entornos sin interferencia directa del desarrollador.", "D) Se hacen antes de que el software esté terminado." ], "correctAnswer": 2, "explanation": "Las pruebas Beta evalúan la madurez y la aceptación del mercado en la naturaleza (in the wild), revelando problemas de hardware y UX no contemplados." },
  { "id": 203, "chapter": 3, "topic": "Proceso de Revisión", "difficulty": "easy", "question": "¿Quién tiene la decisión final sobre qué defectos reportados en una revisión deben ser corregidos?", "options": [ "A) El Moderador.", "B) El Autor del documento.", "C) El Gestor de Recursos Humanos.", "D) Los Revisor(es)." ], "correctAnswer": 1, "explanation": "El autor toma la propiedad de los cambios, analiza los comentarios aportados por los revisores y decide cómo integrar las correcciones." },
  { "id": 204, "chapter": 4, "topic": "Técnicas de Prueba", "difficulty": "medium", "question": "Al aplicar particiones de equivalencia, ¿por qué es suficiente probar solo un valor de una partición válida?", "options": [ "A) Porque los probadores no tienen tiempo.", "B) Porque se asume que si el programa trata un valor de una clase correctamente, tratará a todos los demás valores de esa misma clase de la misma manera.", "C) Porque los demás valores causan caídas.", "D) Porque es lo que pide la ISO." ], "correctAnswer": 1, "explanation": "La teoría matemática de las particiones dicta que todos los valores dentro de una partición son equivalentes (actúan idénticamente) para el sistema lógico." },
  { "id": 205, "chapter": 5, "topic": "Informe de Cierre", "difficulty": "medium", "question": "Al final del proyecto, el Test Summary Report (Informe Resumen de Pruebas) tiene como objetivo:", "options": [ "A) Pedir más presupuesto.", "B) Hacer un resumen de las pruebas ejecutadas frente a las planificadas, lecciones aprendidas y dar una recomendación final de liberación (Release) al comité.", "C) Registrar el primer defecto.", "D) Documentar el código." ], "correctAnswer": 1, "explanation": "Es el documento que consolida todos los datos del proyecto y responde a la pregunta de negocio: '¿Podemos salir a producción de forma segura?'." }
];

data.push(...newQuestions);
fs.writeFileSync(questionsFile, JSON.stringify(data, null, 2));
console.log('Added ' + newQuestions.length + ' new questions. Total is now: ' + data.length);
