const fs = require('fs');

const questionsFile = './src/data/questions.json';
const data = JSON.parse(fs.readFileSync(questionsFile, 'utf8'));

const newQuestions = [
  // Chapter 3: 4 more
  { "id": 241, "chapter": 3, "topic": "Revisiones Estáticas", "difficulty": "medium", "question": "¿Qué técnica de diseño se utiliza MÁS para la revisión estática de la arquitectura antes de escribir código?", "options": [ "A) Análisis Dinámico.", "B) Pruebas Ad-hoc.", "C) Análisis de modelos conceptuales y diagramas UML de la arquitectura.", "D) Análisis de Mutación." ], "correctAnswer": 2, "explanation": "Antes de codificar, las pruebas estáticas se centran en revisar especificaciones técnicas y UML." },
  { "id": 242, "chapter": 3, "topic": "Revisión", "difficulty": "hard", "question": "En las revisiones formales, ¿cuál es el propósito de la fase de 'Fijación de Defectos' (Fixing/Rework)?", "options": [ "A) Reprender al autor públicamente.", "B) El autor del documento corrige los defectos identificados durante la reunión de revisión.", "C) El equipo de pruebas modifica el código de producción en vivo.", "D) Firmar la salida del proyecto." ], "correctAnswer": 1, "explanation": "Tras la revisión, el autor toma los hallazgos y realiza las reparaciones necesarias al documento." },
  { "id": 243, "chapter": 3, "topic": "Herramientas Estáticas", "difficulty": "medium", "question": "¿El análisis estático puede evaluar si una página web cumple con las directrices de accesibilidad (WCAG)?", "options": [ "A) No, eso requiere siempre un humano.", "B) Sí, escaneando el código HTML/CSS en busca de etiquetas alt faltantes o contrastes bajos.", "C) Solo mediante pruebas exploratorias.", "D) No, eso se llama análisis dinámico." ], "correctAnswer": 1, "explanation": "Las herramientas de análisis estático (como las de accesibilidad) escanean la estructura de las páginas sin ejecutarlas interactivamente." },
  { "id": 244, "chapter": 3, "topic": "Listas de Comprobación", "difficulty": "easy", "question": "¿Por qué un revisor novato debería usar una Lista de Comprobación (Checklist) en lugar de revisar de forma libre (Ad-hoc)?", "options": [ "A) Para terminar rápido.", "B) Porque el revisor novato no sabe qué buscar; la lista le da pautas estructuradas sobre errores históricos comunes.", "C) Porque es el único método válido.", "D) Para impresionar al líder." ], "correctAnswer": 1, "explanation": "Una checklist reduce el margen de error humano proporcionando una guía específica sobre qué validar." },
  
  // Chapter 6: 5 more
  { "id": 245, "chapter": 6, "topic": "Rendimiento", "difficulty": "medium", "question": "La herramienta XYZ envía 10.000 peticiones al servidor web en un minuto y mide cuánto tarda en devolver las respuestas. Esta herramienta es de:", "options": [ "A) Cobertura Estática.", "B) Gestión de la Configuración.", "C) Pruebas de Desempeño / Rendimiento (Performance Testing).", "D) ALM." ], "correctAnswer": 2, "explanation": "Las herramientas de rendimiento inyectan carga virtual para probar la escalabilidad del sistema." },
  { "id": 246, "chapter": 6, "topic": "Automatización", "difficulty": "hard", "question": "¿Qué riesgo a largo plazo se asocia con mantener miles de scripts de prueba automatizados GUI (Interfaz de Usuario)?", "options": [ "A) Aumento incontrolado de la motivación del equipo.", "B) El alto costo de mantenimiento por la fragilidad de la interfaz de usuario.", "C) Que el código compilará más rápido.", "D) Fugas de memoria del sistema operativo." ], "correctAnswer": 1, "explanation": "Las pruebas de GUI son frágiles porque los elementos visuales cambian frecuentemente. Si cambias el botón de login, se pueden romper 100 pruebas." },
  { "id": 247, "chapter": 6, "topic": "Clasificación de Herramientas", "difficulty": "easy", "question": "¿Una herramienta de Integración Continua (como Jenkins) pertenece a qué categoría general?", "options": [ "A) Gestión de pruebas y soporte al proceso de ejecución automatizada.", "B) Análisis estático.", "C) Herramienta de modelado.", "D) Preparación de datos." ], "correctAnswer": 0, "explanation": "Jenkins orquesta todo el proceso, compilando y lanzando las suites de prueba automáticamente." },
  { "id": 248, "chapter": 6, "topic": "ROI de Automatización", "difficulty": "medium", "question": "¿Es cierto que las herramientas de automatización pueden encontrar sistemáticamente todos los tipos de defectos mejor que un humano?", "options": [ "A) Sí, las máquinas no cometen errores.", "B) No, las máquinas solo validan lo que se les programó explícitamente (Regresión de expectativas previas). Los humanos encuentran 'Cosas Raras' (Exploración).", "C) Sí, especialmente en usabilidad.", "D) Nunca." ], "correctAnswer": 1, "explanation": "La automatización es excelente comprobando que 'Lo viejo no se rompió' (regresión), pero es terrible explorando para encontrar problemas nuevos." },
  { "id": 249, "chapter": 6, "topic": "PoC", "difficulty": "medium", "question": "Al implantar una herramienta a nivel organizativo, el último paso sugerido suele ser:", "options": [ "A) Hacer la Prueba de Concepto.", "B) Ejecutar un piloto en un equipo real, y si funciona, desplegar al resto de la organización (Roll-out).", "C) Entrenar a los competidores.", "D) Eliminar al equipo QA." ], "correctAnswer": 1, "explanation": "El despliegue escalonado o Roll-out garantiza que las lecciones del piloto se apliquen al resto de la empresa gradualmente." }
];

data.push(...newQuestions);
fs.writeFileSync(questionsFile, JSON.stringify(data, null, 2));
console.log('Added ' + newQuestions.length + ' new questions. Total is now: ' + data.length);
